# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_trash_mgmt_extension
project_short_description: Jupyterlab extension to introduce new left panel (along
    with browser, kernels, git, extensions) to allow management of trash - that is,
    empty bin, remove item from trash, restore item and show how much space items
    in the trash take
python_name: jupyterlab_trash_mgmt_extension
repository: ''
test: true

